

  
    <div class="row d-flex justify-content-left align-items-center h-100 bg-dark">
      
        <div class="card bg-dark " style="border-radius: 15px;">
          <div class="card-body p-4">
            <div class="d-flex text-black">
              <div class="flex-shrink-0">
                <img src="<?php foreach($response['images'] as $k =>$v){
                    echo ($v['url']);
                }  ?>"
                  alt="Generic placeholder image" class="img-fluid"
                  style="width: 180px; border-radius: 10px;">
              </div>
              <div class="flex-grow-1 ms-3">
                <h5 class="mb-1 text-danger"><?php echo $response['display_name'] ?></h5>
                <p class="mb-2 pb-1 text-light" style="color: #2b2a2a;"><?php echo $response['email']; ?></p>
                <div class="d-flex justify-content-start rounded-3 p-2 mb-2"
                  style="background-color: #efefef;">
                  <div>
                    <p class="small text-muted mb-1">Country</p>
                    <p class="mb-0"><?php echo $response['country'] ?></p>
                  </div>
                  <div class="px-3">
                    <p class="small text-muted mb-1">Followers</p>
                    <p class="mb-0"><?php echo $response['followers']['total']; ?></p>
                  </div>
                </div>
                
              </div>
            </div>
          </div>
        </div>
   
    </div>
