<?php if($this->session->has('spotifyId')){
  ?>
    <div class="row d-flex justify-content- align-items-center h-100">
        <div class="card" style="border-radius: 15px;">
          <div class="card-body p-1">
            <div class="d-flex text-black">
              <div class="flex-shrink-0">
              <a href="../index/dashboard" ><img src="<?php foreach($response['images'] as $k =>$v){
                    echo ($v['url']);
                }  ?>"
                  alt="Generic placeholder image" class="img-fluid"
                  style="width: 50px; border-radius: 10px;">
              </div>
              <div class="flex-grow-1 ms-3">
                <h5 class="mb-1"><?php echo $response['display_name'] ?></h5></a>
                <p class="mb-2 pb-1" style="color: #2b2a2a;"><?php echo $response['email']; ?></p>
              </div>
            </div>
          </div>
        </div>
    </div>
<?php }?>
<div class="container-fluid mt-1 mb-3">
    <div class="row justify-content-center">
<?php 
if($response2) 
{ 
    echo "<h4>Recommendations</h4>";
    foreach($response2 as $k=>$v ){
      
 ?>         <div class="col-2 mt-4">
          <div class="card" >
          
         <div class="img-square-wrapper"> <img class="card-img-top" src="<?php echo ($v['album']['images'][0]['url']);
          ?> "  style="" ></div>
            <div class="card-body">
                <p><?php echo $v['name']; ?></p><span><small>(<?php foreach($v['artists'] as $k=>$n){
                    echo $n['name'];
                } ?>)</small></span>
              <form action="../index/addtoplaylist"><button class="btn border-0 btn-success" name="addtoplay" value="<?php echo $v['uri']; ?>" ><small>Add to playlist</small></button></form>
              </div>
            </div>
          </div>
        <?php } }
        
        ?>
    </div>
</div>